apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
      app: nodejs
  ports:
   - port: 8888
       # By default and for convenience, the `targetPort` is set to
       # the same value as the `port` field.
     targetPort: 8888
       # Optional field
       # By default and for convenience, the Kubernetes control plane
       # will allocate a port from a range (default: 30000-32767)
     nodePort: 30010

