apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{.Values.mongo_service.name}}
spec:
  selector:
      app: mongo
  type: {{.Values.mongo_service.type}}    
  ports:
    - protocol: {{.Values.mongo_service.protocol}}
      port: {{.Values.mongo_service.port | default "27017"}}
      targetPort: {{.Values.mongo_service.targetPort | default "27017"}}
  {{- if eq .Values.mongo_service.type "NodePort"}}
      nodePort: {{.Values.mongo_service.nodePort}}    
  {{- end -}} 
