apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: {{.Values.resources.min_memory}}
            cpu: {{.Values.resources.min_cpu}}
          limits:
            memory: {{.Values.resources.max_memory}}
            cpu: {{.Values.resources.max_cpu}}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"

        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc
      #   envFrom:
      #   - secretRef:
      #       name: my-secret
