apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Name}}-my-pv
  labels:
    type: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/ballo/sharedDirForPods # Replace with your NFS export path
    server: 10.0.2.15     # Replace with your NFS server IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
     matchLabels:
       name: {{.Release.Name}}-my-pv
