apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: my-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/ballo/sharedDirForPods # Replace with your NFS export path
    server: 10.0.2.15     # Replace with your NFS server IP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
     matchLabels:
       name: my-pv
