appName: my-nodejs-app
appImage: abdelrhmandevops/devops-task-image

nodejs_service:
  name: nodejs-service
  type: ClusterIP
  port: 8080
  targetPort: 8080
  nodePort: 31000
  # Remove the 'nodePort' line

mongo_service:
  name: mongo-service
  type: ClusterIP
  port: 27017
  targetPort: 27017
  nodePort: 31001
  protocol: TCP

redis_service:
  name: redis-service
  type: ClusterIP
  port: 6379
  targetPort: 6379
  NodePort: 31002
  protocol: TCP

replicas: 
  mongo_replica: 3
  redis_replica: 3
  nodejs_replica: 3

resources:
  min_memory: "100Mi"
  min_cpu: "100m"
  max_memory: "200Mi"
  max_cpu: "100m"

volume:
  sc_name: aws-mongo-sc
  pvc_name: my-pvc
  pvc_storage: "2Gi"
  access_mode: ReadWriteOnce
  path: /data/db

configMap:
  name: my-configs

secret:
  name: my-secrets