apiVersion: v1
kind: Service
metadata:
  name: release-name-mongo-service
  labels:
spec:
  selector:
      app: mongo
  type: ClusterIP    
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

