apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-{{.Values.appName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: {{.Values.replicas.nodejs_replica}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      initContainers:
      - name: init-mongodb
        image: busybox:latest
        command: ["sh", "-c", "until nc -zv {{.Release.Name}}-mongo-service:27017; do echo waiting for MongoDB; sleep 2; done"]
      containers:
      - name: nodejs-container
        image: {{.Values.appImage}}
        resources:
          requests:
            memory: {{.Values.resources.min_memory}}
            cpu: {{.Values.resources.min_cpu}}
          limits:
            memory: {{.Values.resources.max_memory}}
            cpu: {{.Values.resources.max_cpu}}
        envFrom:
        - configMapRef:
            name: {{.Release.Name}}-my-configs
        - secretRef:
            name: {{.Release.Name}}-my-secrets
        