apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-{{.Values.nodejs_service.name}}
spec:
  selector:
    app: {{.Values.appName}}
  type: {{.Values.nodejs_service.type | default "NodePort"}}
  ports:
    - port: {{.Values.nodejs_service.port | default "8080"}}
      targetPort: {{.Values.nodejs_service.targetPort | default "8080"}}
      # nodePort: {{.Values.nodejs_service.nodePort | default "30000" }}
    
