apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}
spec:
  selector:
    app: {{.Values.appName}}
  ports:
    - port: {{.Values.nodejs_service.port}}
      targetPort: {{.Values.nodejs_service.targetPort}}
  type: {{.Values.nodejs_service.type}}
