apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis-service
spec:
  selector:
      app: redis
  ports:
    - protocol: {{.Values.redis_service.protocol}}
      port: {{.Values.redis_service.port}}
      targetPort: {{.Values.redis_service.targetPort}}
  type: {{.Values.redis_service.type}}