apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-redis-deployment
  labels:
    app: redis
spec:
  replicas: {{.Values.replicas.redis_replica}}
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: {{.Values.resources.min_memory}}
            cpu: {{.Values.resources.min_cpu}}
          limits:
            memory: {{.Values.resources.max_memory}}
            cpu: {{.Values.resources.max_cpu}}
